hparams: !!python/object:argparse.Namespace
  accelerator: auto
  alpha: 1.0
  amp: false
  backbone: efficientnet-b7
  batch_size: 1
  cam: false
  ckpt: null
  clamp_val: 0.1
  conda_env: Unet
  datadir: data
  devices: '1'
  epochs: 301
  gamma: 1.0
  gan: false
  lambda_gp: 10
  logsdir: logs
  lr: 0.0001
  n_pts_per_ray: 256
  notification_email: quantm88@gmail.com
  omega: 1.0
  pe: 0
  sh: 0
  shape: 256
  st: 1
  stn: false
  test_samples: 10
  theta: 1.0
  train_samples: 50
  val_samples: 10
  weight_decay: 0.0001
